<a href="https://colab.research.google.com/github/maincarey/ML/blob/master/KFold_Cross_Validation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
digits = load_digits()

In [0]:
# split data right away with data and target
# have to run split many times and check accuracy on all types models

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [0]:
#  use Logistic Regression

lr = LogisticRegression(solver='liblinear',multi_class='ovr')
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9462962962962963

In [0]:
 #  SVM
  svm = SVC(gamma='auto')
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.512962962962963

In [0]:
#  Random Forest


rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9685185185185186

In [0]:
# KFold cross validation
# 
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [0]:
# supply spedicif data set in the array
# this kf.split([1,2,3,4,5,6,7,8,9]) returns an iterator
# divides in to 3 folds the 3 arrays below
# [3 4 5 6 7 8] this is for training    [0 1 2] this fold is for test
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [0]:
# calls model.fit - once its done returns a score using the test sample
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [0]:
# example of how to use method above
get_score(LogisticRegression(), X_train, X_test, y_train, y_test)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


0.9462962962962963

In [0]:
# StratifiedKFold - when separate folds will provide class catregories in unified way - so it evenly distributes types of data
from sklearn.model_selection import StratifiedKFold
# usually use (n_splits=10)  not 3
folds = StratifiedKFold(n_splits=3)


# 
scores_logistic = []
scores_svm = []
scores_rf = []


# same as k split above
for train_index, test_index in folds.split(digits.data,digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
  # measure performance - for loop will go 3 times and append scores in the  array - scores_svm.append
  # add criteria changes inside the types models -LogisticRegression(solver='liblinear',multi_class='ovr')
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))  
    
    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))
    
    # or just print 
    #print(get_score(LogisticRegression(), X_train, X_test, y_train, y_test))  
    #print(get_score(SVC(), X_train, X_test, y_train, y_test))
    #print(get_score(RandomForestClassifier(), X_train, X_test, y_train, y_test))

In [0]:
scores_logistic

[0.8953488372093024, 0.9499165275459098, 0.9093959731543624]

In [0]:
scores_svm

[0.39368770764119604, 0.41068447412353926, 0.4597315436241611]

In [0]:
scores_rf

[0.9235880398671097, 0.9449081803005008, 0.9161073825503355]

In [0]:
#  cross_val_score function
from sklearn.model_selection import cross_val_score

In [0]:
# Logistic regression model performance using cross_val_score
# first argument is classifier second is X the third is Y  
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), digits.data, digits.target,cv=3)

array([0.89534884, 0.94991653, 0.90939597])

In [0]:
# svm model performance using cross_val_score
cross_val_score(SVC(gamma='auto'), digits.data, digits.target,cv=3)

array([0.39368771, 0.41068447, 0.45973154])

In [0]:
# random forest performance using cross_val_score
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target,cv=3)

array([0.93355482, 0.95659432, 0.92449664])

In [0]:
#Parameter tunning using k fold cross validation
scores1 = cross_val_score(RandomForestClassifier(n_estimators=5),digits.data, digits.target, cv=10)
np.average(scores1)

0.8874711333859817

In [0]:
scores2 = cross_val_score(RandomForestClassifier(n_estimators=20),digits.data, digits.target, cv=10)
np.average(scores2)

0.9421552899301334

In [0]:
scores3 = cross_val_score(RandomForestClassifier(n_estimators=30),digits.data, digits.target, cv=10)
np.average(scores3)

0.9495860457893415