<a href="https://colab.research.google.com/github/maincarey/ML/blob/master/save_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt

In [0]:
df = pd.read_csv('/content/sample_data/homes.csv')
df.head()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [0]:
model = linear_model.LinearRegression()
model.fit(df[['area']],df.price)


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [0]:
model.coef_

array([135.78767123])

In [0]:
model.intercept_

180616.43835616432

In [0]:
model.predict([[5000]])

array([859554.79452055])

In [0]:

from sklearn.externals import joblib

/usr/local/lib/python3.6/dist-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)


In [0]:
# joblib can take file name directly
joblib.dump(model, 'model_joblib')

['model_joblib']

In [0]:
# load the file
mj = joblib.load('model_joblib')

In [0]:
mj.coef_

array([135.78767123])

In [0]:
mj.intercept_

180616.43835616432

In [0]:
mj.predict([[5000]])

array([859554.79452055])